# Generated by Django 3.1.3 on 2020-12-25 09:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='itw_counter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('value', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='itw_order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10)])),
                ('code_year', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10)])),
                ('date_register', models.DateField()),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.itw_customer')),
            ],
            options={
                'verbose_name': 'order',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='itw_order_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.itw_order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.itw_product')),
            ],
        ),
        migrations.AddField(
            model_name='itw_order',
            name='product',
            field=models.ManyToManyField(through='order.itw_order_unit', to='product.itw_product'),
        ),
    ]
