# Generated by Django 3.1.3 on 2021-01-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
