# Generated by Django 3.1.3 on 2021-01-19 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210113_2036'),
        ('order', '0003_auto_20210113_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_units', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product'),
        ),
    ]
