# Generated by Django 3.1.3 on 2020-12-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201227_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itw_order',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itw_order',
            name='code_year',
            field=models.IntegerField(),
        ),
    ]
