# Generated by Django 3.1.3 on 2021-01-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210119_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
