# Generated by Django 3.1.3 on 2020-12-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itw_customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=50)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'customer',
                'ordering': ['last_name'],
            },
        ),
    ]
