# Generated by Django 3.1.3 on 2021-01-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default_price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=50)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'product',
                'db_table': 'itw_product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('products', models.ManyToManyField(to='product.Product')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'itw_product_category',
                'ordering': ['name'],
            },
        ),
    ]
