# Generated by Django 3.1.3 on 2020-12-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itw_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('default_price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=50)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='itw_product_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('products', models.ManyToManyField(to='product.itw_product')),
            ],
            options={
                'verbose_name': 'category',
                'ordering': ['name'],
            },
        ),
    ]
