# Generated by Django 3.1.3 on 2021-01-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210112_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='product.ProductCategory'),
        ),
    ]
